### ISSUE TITLE
这要怎么用啊，B站有视频讲解吗

### ISSUE THREAD

**Issue by KuiPer-LTW** [MaaAssistantArknights/MaaAssistantSkland#1]

**Comment by dongwlin** [comment]
除了第一次用要选连接的设备外，其他时候直接启动就好了，推荐配合maa的“结束后脚本”使用；
B站目前是否有视频讲解不太清楚，如果需要的话，可以去B站找maa官号试试（逃

**Comment by KuiPer-LTW** [comment]
> 除了第一次用要选连接的设备外，其他时候直接启动就好了，推荐配合maa的“结束后脚本”使用； B站目前是否有视频讲解不太清楚，如果需要的话，可以去B站找maa官号试试（逃

看了看没有，第一次选择链接设备又要怎么做，我纯小白

**Comment by KuiPer-LTW** [comment]
> 除了第一次用要选连接的设备外，其他时候直接启动就好了，推荐配合maa的“结束后脚本”使用； B站目前是否有视频讲解不太清楚，如果需要的话，可以去B站找maa官号试试（逃

而且我看了一下，这是要图像识别点击来签到的吗？可是森空岛不是装不到模拟器上吗，一直都是显示安装失败的

**Comment by dongwlin** [comment]
> > 除了第一次用要选连接的设备外，其他时候直接启动就好了，推荐配合maa的“结束后脚本”使用； B站目前是否有视频讲解不太清楚，如果需要的话，可以去B站找maa官号试试（逃
> 
> 而且我看了一下，这是要图像识别点击来签到的吗？可是森空岛不是装不到模拟器上吗，一直都是显示安装失败的

是的，MAS是基于图像识别和模拟控制实现的；
如果你的模拟器无法安装森空岛，说明你需要换模拟器了（

**Comment by KuiPer-LTW** [comment]
...

**Comment by KuiPer-LTW** [comment]
> > > 除了第一次用要选连接的设备外，其他时候直接启动就好了，推荐配合maa的“结束后脚本”使用； B站目前是否有视频讲解不太清楚，如果需要的话，可以去B站找maa官号试试（逃
> > 
> > 
> > 而且我看了一下，这是要图像识别点击来签到的吗？可是森空岛不是装不到模拟器上吗，一直都是显示安装失败的
> 
> 是的，MAS是基于图像识别和模拟控制实现的； 如果你的模拟器无法安装森空岛，说明你需要换模拟器了（

...

**Comment by dongwlin** [comment]
README.md 已更新文字说明
