### ISSUE TITLE
运行经常卡住

### ISSUE THREAD

**Issue by Ravio-A** [MaaAssistantArknights/MaaAssistantSkland#10]
具体表现是卡在cmd界面，模拟器显示签到界面但是是前一天的签到界面，
maa会被卡退出
只剩下mas的cmd界面
猜测可能是签到后不退出签到界面导致的问题，手动退出签到界面后无任何问题

**Comment by dongwlin** [comment]
config里有关闭森空岛的选项，启用就好了
