### ISSUE TITLE
能否保存账密在卡登录的时候自动键入

### ISSUE THREAD

**Issue by Private233** [MaaAssistantArknights/MaaAssistantSkland#14]
不知道是软件更新还是时间长了，偶有账号登出然后卡着不动的情况。
能不能保存账密在卡住的时候自动键入以避免进程卡顿
这程序应该不涉及联网 调用接口之类的方面吧，应该没有太大安全问题吧（
![QQ20240806-235724](https://github.com/user-attachments/assets/636e669b-ace3-4fc4-9b93-79f727cb26ed)
![QQ20240807-000127](https://github.com/user-attachments/assets/863e505e-e4fd-444d-884e-17a7cb4a361f)
![QQ20240807-000135](https://github.com/user-attachments/assets/c82edc93-eb15-4034-ad78-1c954d14c5da)

**Comment by ABA2396** [comment]
不做存密码的事情
