### ISSUE TITLE
README 需要更新 MaaPiCli 用法

### ISSUE THREAD

**Issue by zzyyyl** [MaaAssistantArknights/MaaAssistantSkland#15]
MaaPiCli 的用法与之前的 MAS_CLI 大不相同了喵，而且似乎要作为 MAA 的结束后脚本使用很麻烦喵

**Comment by zzyyyl** [comment]
学姐帮帮喵 @ABA2396

**Comment by ABA2396** [comment]
cc @dongwlin 救救）

**Comment by ABA2396** [comment]
这个启动exe之后bat直接就结束了，有什么办法知道MAS跑完了吗

**Comment by dongwlin** [comment]
今天弄弄 ~~（这几天邮件成山了，没看到通知，斯米马赛）~~

**Comment by dongwlin** [comment]
其实和先前差不多的，picli首次使用先配置好任务，后续就直接使用-d参数启动

**Comment by dongwlin** [comment]
> 这个启动exe之后bat直接就结束了，有什么办法知道MAS跑完了吗

啊？启动exe后bat不应该会阻塞等exe跑完吗

**Comment by ABA2396** [comment]
没加 -d 吧）
