### ISSUE TITLE
自动寻找adb不好使怎么办

### ISSUE THREAD

**Issue by Zhuazizizi** [MaaAssistantArknights/MaaAssistantSkland#16]
Please input [1-2]: 1
Finding device...
No device found!
选手动的话，不太懂地址应该填什么，本来抄maa设置里的路径，不过那个有中文似乎不行，所以我下载了个adb尝试了下这么填但运行后无反应也无报错然后自己结束了。
Please input ADB path: E:\MAS\adb
Please input ADB address: 127.0.0.1:16384
![image](https://github.com/user-attachments/assets/31a42ffc-9f98-4cfc-8c6b-126e12c8ade0)

**Comment by dongwlin** [comment]
看样子是adb path错了，是要指向adb的二进制文件

例如：
![image](https://github.com/user-attachments/assets/2ccf9e01-72e7-40a0-9f82-991404ff483e)

即在windows上adb path应该是 `[盘符]\...\adb.exe`

**Comment by Zhuazizizi** [comment]
> 看样子是adb path错了，是要指向adb的二进制文件
> 
> 例如：
> ![image](https://github.com/user-attachments/assets/2ccf9e01-72e7-40a0-9f82-991404ff483e)
> 
> 即在windows上adb path应该是 `[盘符]\...\adb.exe`

好使了。整半天没想起来这个忘了加。感谢。
