### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by SPOPS11** [MaaAssistantArknights/MaaAssistantSkland#20]
![PixPin_2024-09-24_21-23-20](https://github.com/user-attachments/assets/60ef4e0b-2c2c-4441-b430-b57e15855b53)
分辨率设置好了，但还是报错，运行后启动了森空岛APP，然后就没有其他操作了
这是命令提示符的内容
[2024-09-24 21:24:33.540][ERR][Px12928][Tx37670][VisionUtils.hpp][L224][MaaNS::VisionNS::correct_roi] roi is out of range [image.size()=[1280 x 720]] [res=[202 x 133 from (260, 886)]]

**Comment by dongwlin** [comment]
这个报错可以不用理的。你关闭森空岛之后再启动mas看看

**Comment by SPOPS11** [comment]
试过了，还是不可以，启动森空岛后就没有其他动作了

**Comment by dongwlin** [comment]
把日志上传上来看看

**Comment by SPOPS11** [comment]
[maa.log](https://github.com/user-attachments/files/17115614/maa.log)

**Comment by dongwlin** [comment]
看看你森空岛首页的截图

**Comment by SPOPS11** [comment]
![image](https://github.com/user-attachments/assets/7023bb3a-26da-4113-8aba-85edbe1d4d31)

**Comment by dongwlin** [comment]
用mumu模拟器的截图功能截图

**Comment by SPOPS11** [comment]
![MuMu12-20240924-215656](https://github.com/user-attachments/assets/61cc8dcd-d7d7-4146-8104-01a8fb78db94)

**Comment by dongwlin** [comment]
你是调整了什么东西吗，正常来说顶部会有一条状态栏的
![image](https://github.com/user-attachments/assets/d5a19617-fb31-4a5c-9270-9eead6836f2d)

**Comment by SPOPS11** [comment]
我懂了，我把模拟器设置里的后台保活关了就行了，现在可以完美运行了，谢谢

**Comment by MistEO** [comment]
2.0 fw 支持后台保活了，可以更新一下 Release @dongwlin

**Comment by dongwlin** [comment]
> 2.0 fw 支持后台保活了，可以更新一下 Release @dongwlin 

目前有部分任务依靠多roi，且不能用较大的roi替代。现在得研究一下其他方案才能更新到2.0

**Comment by MistEO** [comment]
> > 2.0 fw 支持后台保活了，可以更新一下 Release @dongwlin
> 
> 目前有部分任务依靠多roi，且不能用较大的roi替代。现在得研究一下其他方案才能更新到2.0

拆成多个任务就好了（确信
