### ISSUE TITLE
这是没有检测到的意思吗，，但我MAA正常的

### ISSUE THREAD

**Issue by WSMTBG** [MaaAssistantArknights/MaaAssistantSkland#4]
![图片](https://github.com/MaaAssistantArknights/MaaAssistantSkland/assets/32087250/842245df-76f7-4ad9-80a2-b5dc6cc9189c)
![图片](https://github.com/MaaAssistantArknights/MaaAssistantSkland/assets/32087250/c92d6249-c656-478e-95e5-27c8ed6f0af5)

**Comment by WSMTBG** [comment]
管理员启动可以检测，但为什么重复了...选了以后这个又是什么情况....看不懂...
![图片](https://github.com/MaaAssistantArknights/MaaAssistantSkland/assets/32087250/e3c7bfd9-3274-4e14-b3ca-0326652d8d89)

**Comment by dongwlin** [comment]
你有看过文档的 [直接使用](https://github.com/MaaAssistantArknights/MaaAssistantSkland#%E7%9B%B4%E6%8E%A5%E4%BD%BF%E7%94%A8) 这一部分吗

**Comment by dongwlin** [comment]
> 管理员启动可以检测，但为什么重复了...选了以后这个又是什么情况....看不懂... ![图片](https://user-images.githubusercontent.com/32087250/270237070-e3c7bfd9-3274-4e14-b3ca-0326652d8d89.png)

设备重复的问题暂时不清楚，选择好需要连接的设备后就会开始运行了

**Comment by dongwlin** [comment]
> 管理员启动可以检测，但为什么重复了...选了以后这个又是什么情况....看不懂... ![图片](https://user-images.githubusercontent.com/32087250/270237070-e3c7bfd9-3274-4e14-b3ca-0326652d8d89.png)

@MistEO 玛丽！

**Comment by WSMTBG** [comment]
> > 管理员启动可以检测，但为什么重复了...选了以后这个又是什么情况....看不懂... ![图片](https://user-images.githubusercontent.com/32087250/270237070-e3c7bfd9-3274-4e14-b3ca-0326652d8d89.png)
> 
> @MistEO 玛丽！

现在情况就是无限打开森空岛但不签到...想要我提供什么吗

**Comment by WSMTBG** [comment]
蓝叠版本5.10.220.1008 N64
win11 22H2 家庭版
[maa.log](https://github.com/MaaAssistantArknights/MaaAssistantSkland/files/12711569/maa.log)

**Comment by WSMTBG** [comment]
可能是因为我MAA是管理员的，所以MAS也只能管理员，现在我MAA普通启动，正常能用，MAS普通启动，能检测，但还是一直打开森空岛但不签到，模拟器分辨率是1920*1080的
[maa.log](https://github.com/MaaAssistantArknights/MaaAssistantSkland/files/12711702/maa.log)

**Comment by dongwlin** [comment]
> 可能是因为我MAA是管理员的，所以MAS也只能管理员，现在我MAA普通启动，正常能用，MAS普通启动，能检测，但还是一直打开森空岛但不签到，模拟器分辨率是1920*1080的 [maa.log](https://github.com/MaaAssistantArknights/MaaAssistantSkland/files/12711702/maa.log)

请根据 [适配情况](https://github.com/MaaAssistantArknights/MaaAssistantSkland#%E9%80%82%E9%85%8D%E6%83%85%E5%86%B5) 修改模拟器dpi

**Comment by WSMTBG** [comment]
> > 可能是因为我MAA是管理员的，所以MAS也只能管理员，现在我MAA普通启动，正常能用，MAS普通启动，能检测，但还是一直打开森空岛但不签到，模拟器分辨率是1920*1080的  [maa.log ](https://github.com/MaaAssistantArknights/MaaAssistantSkland/files/12711702/maa.log)
> 
> 请根据 [适配情况 ](https://github.com/MaaAssistantArknights/MaaAssistantSkland#%E9%80%82%E9%85%8D%E6%83%85%E5%86%B5) 修改模拟器dpi

原来如此，我大意了，谢谢
