### ISSUE TITLE
求问大佬程序一直卡在skland running怎么办

### ISSUE THREAD

**Issue by ygb666** [MaaAssistantArknights/MaaAssistantSkland#7]
可以打开森空岛，但是一直停留在首页，不进行签到，求帮忙看看，谢谢各位大佬~
![image](https://github.com/MaaAssistantArknights/MaaAssistantSkland/assets/60098049/99f35f4a-f88b-4a06-80dd-f62b5b4299b8)
![image](https://github.com/MaaAssistantArknights/MaaAssistantSkland/assets/60098049/3bf57a0e-c3c0-4b54-8474-6635bdabf0e6)
[maa.log](https://github.com/MaaAssistantArknights/MaaAssistantSkland/files/13238311/maa.log)

**Comment by zmy1828** [comment]
分辨率设置的不对，目前只有1280x720 320dpi和1920x1080 480dpi分辨率

**Comment by MistEO** [comment]
截个图看看你这两个地方怎么设置的

![image](https://github.com/MaaAssistantArknights/MaaAssistantSkland/assets/18511905/95217328-10d2-4353-b632-a04d479df9d1)
![image](https://github.com/MaaAssistantArknights/MaaAssistantSkland/assets/18511905/b55dbca2-b5f7-4aa0-a346-61b2e173f9db)

**Comment by dongwlin** [comment]
你该不会是开了mumu12的分屏功能吧？

**Comment by moomiji** [comment]
config.json 里 screencap 用这两个 4: Encode, 5: EncodeToFile

**Comment by ygb666** [comment]
感谢各位大佬，这边试了下把图中的“后台挂机时保活运行”关了就正常了
![image](https://github.com/MaaAssistantArknights/MaaAssistantSkland/assets/60098049/5716b637-ab41-4e35-9bc5-ea368ec0ca2a)
