### ISSUE TITLE
什么时候能和MAA统一分辨率设置？

### ISSUE THREAD

**Issue by zmy1828** [MaaAssistantArknights/MaaAssistantSkland#8]
目前可用的两个分辨率都与MAA不兼容，无法正常截图

**Comment by ABA2396** [comment]
maa 1280x720和1920x1080不是都支持的吗

**Comment by dongwlin** [comment]
为啥会不兼容？

**Comment by moomiji** [comment]
config.json 里 screencap 用这两个 4: Encode, 5: EncodeToFile

**Comment by zmy1828** [comment]
> maa 1280x720和1920x1080不是都支持的吗

dpi设置问题，森空岛签到程序需要1280x720 320dpi，模拟器默认选项只有1280x720 240dpi，这种情况下无法正常签到，自定设置为320dpi以后maa又会报错，截图失败

**Comment by dongwlin** [comment]
> > maa 1280x720和1920x1080不是都支持的吗
> 
> dpi设置问题，森空岛签到程序需要1280x720 320dpi，模拟器默认选项只有1280x720 240dpi，这种情况下无法正常签到，自定设置为320dpi以后maa又会报错，截图失败

![image](https://github.com/MaaAssistantArknights/MaaAssistantSkland/assets/97545700/0ea2a331-8a30-4e19-a352-86c1d7138a2e)
不知道你怎么设置的，但我这样两者都是正常的，或许你应该查看maa截图失败的原因
